[package]
name = "bamboo"
version = "0.1.0"
authors = ["Joe Chasinga <jo.chasinga@gmail.com>"]
edition = "2018"
description = "A proxy that throttles network in real-time"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5"